### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by ligi**
mainly wanted the "attach resources" and did the other stuff in the process

### CODE REVIEW

**Comment by tingyik90** [comment]
Hi @ligi, thanks for this pull request! But I am rather reluctant to use gradle 6.0.1 since the latest stable is 5.4.1. I've upgraded gradle in commit https://github.com/tingyik90/snackprogressbar/commit/60d2891b1b81a88802d2172cb0ffa9a0fb6c3e84.

Other changes that you made are for the `app` section, which is not really a concern since that is for demo purpose only.

**Comment by ligi** [comment]
thanks for looking into this. Do not yet understand where 5.4.1 is the latest stable - AFAIK it is 6.0.1: https://github.com/gradle/gradle/releases
Anyway - do not care for the gradle version that much - but really want attached sources.

**Comment by tingyik90** [comment]
I'm looking at https://developer.android.com/studio/releases/gradle-plugin#updating-gradle, where there seems to be a limit up to gradle 5.6.4. So I'd like to keep it as default that is suggested by Android Studio.

As for attached sources, I'm not familiar with what https://github.com/tingyik90/snackprogressbar/pull/25/commits/a7e31362824b431c2272d6c45f4da193ce3ef608 will generate. Do you mind pointing out some explanation of what it does? Sorry about that as I'm not familiar with gradle besides of what I normally use. I'll look into it this week as it's 2 AM local time now. Thanks.

**Comment by ligi** [comment]
it publishes the sources as artifacts - so when consuming the library I can click on the function and see the sources - quite important to me

**Pull request closed without merging**
